//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIAss1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelDetail
    {
        public string HotelName { get; set; }
        public string HotelType { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
